# Generated by Django 3.0.5 on 2021-02-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
